- platform: template
  sensors:
    current_activity:
      entity_id: remote.harmony_hub
      friendly_name: 'Current Activity'
      value_template: >
        {% if is_state("remote.harmony_hub", 'on') %}
          {{ states.remote.harmony_hub.attributes.current_activity }}
        {% else %}
          PowerOff
        {% endif %}
      #  value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'

# - platform: plex
  # host: 192.168.1.137
